# NumPy

NumPy es una libreria de algebra linear para Python, Esta libreria es particularmente importante por que el resto de librerías de cómputo científico dependen de ella de alguna manera 

NumPy es icreiblemente rapido a comparacion del manejo de listas en python. si quieren saber por que usar arreglos en lugar de listas pueden checarlo en [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

In [ ]:
import numpy as np

# Arreglos

In [ ]:
mylist=[1,2,3]
mylist

[1, 2, 3]

In [ ]:
np.array(mylist)

array([1, 2, 3])

In [ ]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Creación de arreglos y matrices  
## Secuenciales

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

## Ceros y Unos 

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Con separaciones iguales

In [ ]:
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## Matriz identidad 

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Aleatorias

In [ ]:
np.random.rand(2)

array([0.6460056 , 0.50865598])

In [ ]:
np.random.rand(5,5)

array([[0.62837617, 0.08365354, 0.47602442, 0.61591405, 0.74790574],
       [0.7802593 , 0.1682082 , 0.1639358 , 0.53856588, 0.32738366],
       [0.91410205, 0.33150083, 0.24705275, 0.84890722, 0.13693604],
       [0.16518394, 0.49238824, 0.95234838, 0.46649672, 0.82583963],
       [0.89137575, 0.68542323, 0.57409623, 0.11069067, 0.0389268 ]])

In [ ]:
np.random.randn(2)

array([-0.541603  , -1.21237113])

In [ ]:
np.random.randn(2,2)

array([[-1.50466052,  0.70311089],
       [-1.71821607,  0.81869379]])

In [ ]:
np.random.randint(1,99)

87

In [ ]:
np.random.randint(1,99,10)

array([21, 81, 28, 62, 20, 23, 94, 65, 55, 23])

# Atributos y métodos 

In [ ]:
arr=np.arange(25)
randarr=np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
randarr

array([29, 23,  0, 35, 37, 15,  7, 14,  7, 25])

## Cambiar forma de los arreglos

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## Encontrar maximos y minimos

In [ ]:
randarr

array([29, 23,  0, 35, 37, 15,  7, 14,  7, 25])

In [ ]:
randarr.max()

37

In [ ]:
randarr.argmax()

4

In [ ]:
randarr.min()

0

In [ ]:
randarr.argmin()

2

## Analizar la forma de los arreglos

In [ ]:
arr.shape

(25,)

In [ ]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.dtype

dtype('int32')

## Indexación de arreglos 

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr[8]

8

In [ ]:
arr[1:8]

array([1, 2, 3, 4, 5, 6, 7])

## Asignaciones múltiples

In [ ]:
arr[0:5]=100

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [ ]:
slice_arr=arr[6:10]

In [ ]:
slice_arr

array([6, 7, 8, 9])

In [ ]:
slice_arr[0:4]=99

In [ ]:
slice_arr

array([99, 99, 99, 99])

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,  99,  99,  99,  99,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [ ]:
arr_copy=arr.copy()
arr_copy

array([100, 100, 100, 100, 100,   5,  99,  99,  99,  99,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [ ]:
arr_copy[0:20]=20

In [ ]:
arr_copy

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 21, 22, 23, 24])

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,  99,  99,  99,  99,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

## Indexación de matrices 

In [ ]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d[1]

array([4, 5, 6])

In [ ]:
arr2d[1][1]

5

In [ ]:
arr2d[1,1]

5

In [ ]:
arr2d[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d.shape

(3, 3)

In [ ]:
arr2d[arr2d.shape[1]-1]

array([7, 8, 9])

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,  99,  99,  99,  99,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [ ]:
arrbol=arr > 21
arrbol

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True])

In [ ]:
arr[arrbol]

array([100, 100, 100, 100, 100,  99,  99,  99,  99,  22,  23,  24])

In [ ]:
arr[arr<21]

array([ 5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# Aritmética

In [ ]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr/arr

C:\Users\Flintlock\Anaconda3\envs\tensorflowCPUdemo\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1/arr

C:\Users\Flintlock\Anaconda3\envs\tensorflowCPUdemo\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

## Funciones universales de Numpy

Numpy tiene una serie de [funciones universales](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), que permiten hacer una serie de operaciones matemáticas.

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

C:\Users\Flintlock\Anaconda3\envs\tensorflowCPUdemo\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
np.max(arr)